<a href="https://colab.research.google.com/github/divyashriashokan/Prep_insta_Internship/blob/main/Web_Scraping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [256]:
import requests
from bs4 import BeautifulSoup as bs

In [257]:
url = 'https://books.toscrape.com/'

response = requests.get(url)
response

In [258]:
response.status_code

200

In [259]:
soup = bs(response.text)
type(soup)

bs4.BeautifulSoup

In [260]:
books_tag = soup.find_all('article',class_ = 'product_pod')

In [261]:
len(books_tag)

20

In [262]:
book = books_tag[0]
print(book)

<article class="product_pod">
<div class="image_container">
<a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
<div class="product_price">
<p class="price_color">Â£51.77</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>

In [255]:
# Finding title of book

title_tag = book.find('a',title=True)
title = title_tag['title']
title

'Deliciously Ella Every Day: Quick and Easy Recipes for Gluten-Free Snacks, Packed Lunches, and Simple Meals'

In [225]:
# Getting the rating of book

rating = book.find('p')['class'][1]
print(rating)

Three

In [226]:
# Getting the price of book

price = book.find('p',class_="price_color")
price = price.text.strip('Â')

In [227]:
link = book.find('a')['href']
print(link)

catalogue/a-light-in-the-attic_1000/index.html

In [228]:
#Getting link for book

book_link = url+link
book_link

'https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html'

## Adding the scraped information to a Pandas Dataframe

In [237]:
import pandas as pd

In [238]:
df = pd.DataFrame()

In [ ]:
x = {'title':title, 'rating':rating,'price':price,'link':book_link}

df=df.append(x,ignore_index = True)

In [ ]:
# Using for loop to get the information of 20 books in a page

for i in range(20):
    book = books_tag[i]

    title_tag = book.find('a',title=True)
    title = title_tag['title']

    rating = book.find('p')['class'][1]

    price = book.find('p',class_="price_color")
    price = price.text.strip('Â')

    link = book.find('a')['href']
    book_link = url+link

    x = {'title':title, 'rating':rating,'price':price,'link':book_link}

    df =df.append(x,ignore_index = True)

In [ ]:
df

In [234]:
# Defining a function to get the info of each book that will be looped

def page(book):

    title_tag = book.find('a',title=True)
    title = title_tag['title']

    rating = book.find('p')['class'][1]

    price = book.find('p',class_="price_color")
    price = price.text.strip('Â')

    link = book.find('a')['href']
    book_link = url+link

    x = {'title':title, 'rating':rating,'price':price,'link':book_link}

    return x

In [ ]:
# Looping the url by changing the page number and getting to scrape 10 pages consisting of 200 books

url2 = 'https://books.toscrape.com/catalogue/page-2.html'
response = requests.get(url2)
soup2 = bs(response.text)
books_tag2 = soup2.find_all('article',class_='product_pod')
for i in range(20):
    book = books_tag2[i]
    temp = page(book)
    df = df.append(temp,ignore_index = True)

## Combining all the above steps into a single block.
## Creting a new df called books_df which has the information of books from 10 pages

In [263]:
books_df  = pd.DataFrame(columns=['title','rating','price','link'])
books_df

Empty DataFrame
Columns: [title, rating, price, link]
Index: []

In [ ]:
url = 'https://books.toscrape.com/catalogue/page-1.html'
for i in range(0,10):
  url1 = url.replace('1',str(i+1))
  response = requests.get(url1)
  soup = bs(response.text)
  books_tag = soup.find_all('article',class_='product_pod')
  for i in range(20):
      book = books_tag[i]
      temp = page(book)
      books_df = books_df.append(temp,ignore_index = True)

In [265]:
books_df

,title,rating,price,link
0,A Light in the Attic,Three,£51.77,https://books.toscrape.com/catalogue/page-1.ht...
1,Tipping the Velvet,One,£53.74,https://books.toscrape.com/catalogue/page-1.ht...
2,Soumission,One,£50.10,https://books.toscrape.com/catalogue/page-1.ht...
3,Sharp Objects,Four,£47.82,https://books.toscrape.com/catalogue/page-1.ht...
4,Sapiens: A Brief History of Humankind,Five,£54.23,https://books.toscrape.com/catalogue/page-1.ht...
...,...,...,...,...
195,Eureka Trivia 6.0,Four,£54.59,https://books.toscrape.com/catalogue/page-1.ht...
196,Drive: The Surprising Truth About What Motivat...,Four,£34.95,https://books.toscrape.com/catalogue/page-1.ht...
197,Done Rubbed Out (Reightman & Bailey #1),Five,£37.72,https://books.toscrape.com/catalogue/page-1.ht...
198,Doing It Over (Most Likely To #1),Three,£35.61,https://books.toscrape.com/catalogue/page-1.ht...
199,Deliciously Ella Every Day: Quick and Easy Rec...,Three,£42.16,https://books.toscrape.com/catalogue/page-1.ht...

As we can see the rows are all right aligned in the books_df. So making it all left aligned for uniformity and better readability

In [266]:
left_aligned_df = books_df.style.set_properties(**{'text-align': 'left'})

left_aligned_df = left_aligned_df.set_table_styles(
    [dict(selector='th', props=[('text-align', 'left')])])

In [267]:
left_aligned_df